-- liquibase formatted sql
-- changeset liquibaseuser:1

-- Autogenerated: do not edit this file

CREATE TABLE cache_accounts.account (
    id text NOT NULL,
    name text NOT NULL,
    first_nm text NULL,
    last_nm text NULL,
    email text NULL,
    phone text NULL,
    PRIMARY KEY (ID)
);

-- rollback drop table account;