spring.data.gemfire.pool.locators=127.0.0.1[10001]
spring.data.gemfire.pool.read-timeout=10000
spring.data.gemfire.pool.default.pr-single-hop-enabled=true
spring.data.gemfire.pool.max-connections=40
spring.data.gemfire.pool.min-connections=10
gemfire.cluster.2.locator.host=127.0.0.1
gemfire.cluster.2.locator.port=10002
app.sleepMs=1000
app.circuit.breaker.timeout.seconds=1
#app.circuit.breaker.cancel.running.future=false