spring.data.gemfire.pool.locators=127.0.0.1[10001]
spring.data.gemfire.pool.read-timeout=10000
spring.data.gemfire.pool.default.pr-single-hop-enabled=true
spring.data.gemfire.pool.max-connections=40
spring.data.gemfire.pool.min-connections=10
app.sleepMs=1000