management.endpoints.web.exposure.include: "*"
gemfire:
  server:
    name: account-server-1
  async:
    event:
      queue:
        id: account-server-queue
  start-locator: "localhost[10334]"
  locators: "localhost[10334]"
flyway:
  locations: "classpath:db/migration"
server:
  port: 6003
spring:
  application:
    name: account-server
  data:
    gemfire:
      pool:
        locators: localhost[10334]
